development:
  server: "http://localhost:9292/faye"
  secret_token: "privatepub"
test:
  server: "http://localhost:9292/faye"
  secret_token: "privatepub"
production:
  server: "http://livepost-backend.herokuapp.com/faye"
  secret_token: "privatepub"
  signature_expiration: 3600 # one hour
